//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  philosophy: Philosophy;
  philosophyConnection: PhilosophyConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  work: Work;
  workConnection: WorkConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryPhilosophyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhilosophyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryWorkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  philosophy?: InputMaybe<PhilosophyFilter>;
  services?: InputMaybe<ServicesFilter>;
  contact?: InputMaybe<ContactFilter>;
  work?: InputMaybe<WorkFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Philosophy | Services | Contact | Work | Folder;

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroButtonText?: Maybe<Scalars['String']['output']>;
  introLabel?: Maybe<Scalars['String']['output']>;
  introHeading?: Maybe<Scalars['String']['output']>;
  introBody1?: Maybe<Scalars['JSON']['output']>;
  introBody2?: Maybe<Scalars['JSON']['output']>;
  burgundyHeading?: Maybe<Scalars['String']['output']>;
  servicesLabel?: Maybe<Scalars['String']['output']>;
  servicesHeading?: Maybe<Scalars['String']['output']>;
  servicesSubtext?: Maybe<Scalars['String']['output']>;
  marqueeText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageFilter = {
  heroSubtitle?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroButtonText?: InputMaybe<StringFilter>;
  introLabel?: InputMaybe<StringFilter>;
  introHeading?: InputMaybe<StringFilter>;
  introBody1?: InputMaybe<RichTextFilter>;
  introBody2?: InputMaybe<RichTextFilter>;
  burgundyHeading?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  servicesHeading?: InputMaybe<StringFilter>;
  servicesSubtext?: InputMaybe<StringFilter>;
  marqueeText?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type PhilosophyPillars = {
  __typename?: 'PhilosophyPillars';
  number?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
};

export type Philosophy = Node & Document & {
  __typename?: 'Philosophy';
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  marqueeText?: Maybe<Scalars['String']['output']>;
  shiftLabel?: Maybe<Scalars['String']['output']>;
  shiftHeading?: Maybe<Scalars['String']['output']>;
  shiftLead?: Maybe<Scalars['JSON']['output']>;
  shiftBody1?: Maybe<Scalars['String']['output']>;
  shiftBody2?: Maybe<Scalars['String']['output']>;
  burgundyQuote?: Maybe<Scalars['String']['output']>;
  promiseLabel?: Maybe<Scalars['String']['output']>;
  promiseHeading?: Maybe<Scalars['String']['output']>;
  pillars?: Maybe<Array<Maybe<PhilosophyPillars>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhilosophyPillarsFilter = {
  number?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type PhilosophyFilter = {
  heroSubtitle?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  marqueeText?: InputMaybe<StringFilter>;
  shiftLabel?: InputMaybe<StringFilter>;
  shiftHeading?: InputMaybe<StringFilter>;
  shiftLead?: InputMaybe<RichTextFilter>;
  shiftBody1?: InputMaybe<StringFilter>;
  shiftBody2?: InputMaybe<StringFilter>;
  burgundyQuote?: InputMaybe<StringFilter>;
  promiseLabel?: InputMaybe<StringFilter>;
  promiseHeading?: InputMaybe<StringFilter>;
  pillars?: InputMaybe<PhilosophyPillarsFilter>;
};

export type PhilosophyConnectionEdges = {
  __typename?: 'PhilosophyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Philosophy>;
};

export type PhilosophyConnection = Connection & {
  __typename?: 'PhilosophyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhilosophyConnectionEdges>>>;
};

export type ServicesServices = {
  __typename?: 'ServicesServices';
  id?: Maybe<Scalars['String']['output']>;
  number?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  capabilities?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  marqueeText?: Maybe<Scalars['String']['output']>;
  introLabel?: Maybe<Scalars['String']['output']>;
  introHeading?: Maybe<Scalars['String']['output']>;
  introBody?: Maybe<Scalars['String']['output']>;
  burgundyHeading?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<ServicesServices>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesServicesFilter = {
  id?: InputMaybe<StringFilter>;
  number?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  capabilities?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  heroSubtitle?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  marqueeText?: InputMaybe<StringFilter>;
  introLabel?: InputMaybe<StringFilter>;
  introHeading?: InputMaybe<StringFilter>;
  introBody?: InputMaybe<StringFilter>;
  burgundyHeading?: InputMaybe<StringFilter>;
  services?: InputMaybe<ServicesServicesFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  marqueeText?: Maybe<Scalars['String']['output']>;
  introLabel?: Maybe<Scalars['String']['output']>;
  introHeading?: Maybe<Scalars['String']['output']>;
  introBody?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  heroSubtitle?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  marqueeText?: InputMaybe<StringFilter>;
  introLabel?: InputMaybe<StringFilter>;
  introHeading?: InputMaybe<StringFilter>;
  introBody?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Work = Node & Document & {
  __typename?: 'Work';
  clientName?: Maybe<Scalars['String']['output']>;
  industry?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  setupHeading?: Maybe<Scalars['String']['output']>;
  setupBody?: Maybe<Scalars['String']['output']>;
  catalystHeading?: Maybe<Scalars['String']['output']>;
  catalystBody?: Maybe<Scalars['String']['output']>;
  resolutionHeading?: Maybe<Scalars['String']['output']>;
  resolutionBody?: Maybe<Scalars['String']['output']>;
  impactStatement?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type WorkFilter = {
  clientName?: InputMaybe<StringFilter>;
  industry?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  setupHeading?: InputMaybe<StringFilter>;
  setupBody?: InputMaybe<StringFilter>;
  catalystHeading?: InputMaybe<StringFilter>;
  catalystBody?: InputMaybe<StringFilter>;
  resolutionHeading?: InputMaybe<StringFilter>;
  resolutionBody?: InputMaybe<StringFilter>;
  impactStatement?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
};

export type WorkConnectionEdges = {
  __typename?: 'WorkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Work>;
};

export type WorkConnection = Connection & {
  __typename?: 'WorkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorkConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updatePhilosophy: Philosophy;
  createPhilosophy: Philosophy;
  updateServices: Services;
  createServices: Services;
  updateContact: Contact;
  createContact: Contact;
  updateWork: Work;
  createWork: Work;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationCreatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};


export type MutationCreateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  work?: InputMaybe<WorkMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  work?: InputMaybe<WorkMutation>;
};

export type HomepageMutation = {
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroButtonText?: InputMaybe<Scalars['String']['input']>;
  introLabel?: InputMaybe<Scalars['String']['input']>;
  introHeading?: InputMaybe<Scalars['String']['input']>;
  introBody1?: InputMaybe<Scalars['JSON']['input']>;
  introBody2?: InputMaybe<Scalars['JSON']['input']>;
  burgundyHeading?: InputMaybe<Scalars['String']['input']>;
  servicesLabel?: InputMaybe<Scalars['String']['input']>;
  servicesHeading?: InputMaybe<Scalars['String']['input']>;
  servicesSubtext?: InputMaybe<Scalars['String']['input']>;
  marqueeText?: InputMaybe<Scalars['String']['input']>;
};

export type PhilosophyPillarsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type PhilosophyMutation = {
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  marqueeText?: InputMaybe<Scalars['String']['input']>;
  shiftLabel?: InputMaybe<Scalars['String']['input']>;
  shiftHeading?: InputMaybe<Scalars['String']['input']>;
  shiftLead?: InputMaybe<Scalars['JSON']['input']>;
  shiftBody1?: InputMaybe<Scalars['String']['input']>;
  shiftBody2?: InputMaybe<Scalars['String']['input']>;
  burgundyQuote?: InputMaybe<Scalars['String']['input']>;
  promiseLabel?: InputMaybe<Scalars['String']['input']>;
  promiseHeading?: InputMaybe<Scalars['String']['input']>;
  pillars?: InputMaybe<Array<InputMaybe<PhilosophyPillarsMutation>>>;
};

export type ServicesServicesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  number?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  capabilities?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesMutation = {
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  marqueeText?: InputMaybe<Scalars['String']['input']>;
  introLabel?: InputMaybe<Scalars['String']['input']>;
  introHeading?: InputMaybe<Scalars['String']['input']>;
  introBody?: InputMaybe<Scalars['String']['input']>;
  burgundyHeading?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<ServicesServicesMutation>>>;
};

export type ContactMutation = {
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  marqueeText?: InputMaybe<Scalars['String']['input']>;
  introLabel?: InputMaybe<Scalars['String']['input']>;
  introHeading?: InputMaybe<Scalars['String']['input']>;
  introBody?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type WorkMutation = {
  clientName?: InputMaybe<Scalars['String']['input']>;
  industry?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  setupHeading?: InputMaybe<Scalars['String']['input']>;
  setupBody?: InputMaybe<Scalars['String']['input']>;
  catalystHeading?: InputMaybe<Scalars['String']['input']>;
  catalystBody?: InputMaybe<Scalars['String']['input']>;
  resolutionHeading?: InputMaybe<Scalars['String']['input']>;
  resolutionBody?: InputMaybe<Scalars['String']['input']>;
  impactStatement?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepagePartsFragment = { __typename: 'Homepage', heroSubtitle?: string | null, heroTitle?: string | null, heroButtonText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody1?: any | null, introBody2?: any | null, burgundyHeading?: string | null, servicesLabel?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, marqueeText?: string | null };

export type PhilosophyPartsFragment = { __typename: 'Philosophy', heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, shiftLabel?: string | null, shiftHeading?: string | null, shiftLead?: any | null, shiftBody1?: string | null, shiftBody2?: string | null, burgundyQuote?: string | null, promiseLabel?: string | null, promiseHeading?: string | null, pillars?: Array<{ __typename: 'PhilosophyPillars', number?: string | null, title?: string | null, body?: string | null, quote?: string | null } | null> | null };

export type ServicesPartsFragment = { __typename: 'Services', heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, burgundyHeading?: string | null, services?: Array<{ __typename: 'ServicesServices', id?: string | null, number?: string | null, title?: string | null, body?: string | null, capabilities?: Array<string | null> | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, email?: string | null, phone?: string | null, location?: string | null };

export type WorkPartsFragment = { __typename: 'Work', clientName?: string | null, industry?: string | null, heroImage?: string | null, setupHeading?: string | null, setupBody?: string | null, catalystHeading?: string | null, catalystBody?: string | null, resolutionHeading?: string | null, resolutionBody?: string | null, impactStatement?: string | null, published?: boolean | null };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, heroSubtitle?: string | null, heroTitle?: string | null, heroButtonText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody1?: any | null, introBody2?: any | null, burgundyHeading?: string | null, servicesLabel?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, marqueeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, heroSubtitle?: string | null, heroTitle?: string | null, heroButtonText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody1?: any | null, introBody2?: any | null, burgundyHeading?: string | null, servicesLabel?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, marqueeText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PhilosophyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhilosophyQuery = { __typename?: 'Query', philosophy: { __typename: 'Philosophy', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, shiftLabel?: string | null, shiftHeading?: string | null, shiftLead?: any | null, shiftBody1?: string | null, shiftBody2?: string | null, burgundyQuote?: string | null, promiseLabel?: string | null, promiseHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pillars?: Array<{ __typename: 'PhilosophyPillars', number?: string | null, title?: string | null, body?: string | null, quote?: string | null } | null> | null } };

export type PhilosophyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
}>;


export type PhilosophyConnectionQuery = { __typename?: 'Query', philosophyConnection: { __typename?: 'PhilosophyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhilosophyConnectionEdges', cursor: string, node?: { __typename: 'Philosophy', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, shiftLabel?: string | null, shiftHeading?: string | null, shiftLead?: any | null, shiftBody1?: string | null, shiftBody2?: string | null, burgundyQuote?: string | null, promiseLabel?: string | null, promiseHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pillars?: Array<{ __typename: 'PhilosophyPillars', number?: string | null, title?: string | null, body?: string | null, quote?: string | null } | null> | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, burgundyHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'ServicesServices', id?: string | null, number?: string | null, title?: string | null, body?: string | null, capabilities?: Array<string | null> | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, burgundyHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'ServicesServices', id?: string | null, number?: string | null, title?: string | null, body?: string | null, capabilities?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, email?: string | null, phone?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, heroSubtitle?: string | null, heroTitle?: string | null, marqueeText?: string | null, introLabel?: string | null, introHeading?: string | null, introBody?: string | null, email?: string | null, phone?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WorkQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WorkQuery = { __typename?: 'Query', work: { __typename: 'Work', id: string, clientName?: string | null, industry?: string | null, heroImage?: string | null, setupHeading?: string | null, setupBody?: string | null, catalystHeading?: string | null, catalystBody?: string | null, resolutionHeading?: string | null, resolutionBody?: string | null, impactStatement?: string | null, published?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WorkConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkFilter>;
}>;


export type WorkConnectionQuery = { __typename?: 'Query', workConnection: { __typename?: 'WorkConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WorkConnectionEdges', cursor: string, node?: { __typename: 'Work', id: string, clientName?: string | null, industry?: string | null, heroImage?: string | null, setupHeading?: string | null, setupBody?: string | null, catalystHeading?: string | null, catalystBody?: string | null, resolutionHeading?: string | null, resolutionBody?: string | null, impactStatement?: string | null, published?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  heroSubtitle
  heroTitle
  heroButtonText
  introLabel
  introHeading
  introBody1
  introBody2
  burgundyHeading
  servicesLabel
  servicesHeading
  servicesSubtext
  marqueeText
}
    `;
export const PhilosophyPartsFragmentDoc = gql`
    fragment PhilosophyParts on Philosophy {
  __typename
  heroSubtitle
  heroTitle
  marqueeText
  shiftLabel
  shiftHeading
  shiftLead
  shiftBody1
  shiftBody2
  burgundyQuote
  promiseLabel
  promiseHeading
  pillars {
    __typename
    number
    title
    body
    quote
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  heroSubtitle
  heroTitle
  marqueeText
  introLabel
  introHeading
  introBody
  burgundyHeading
  services {
    __typename
    id
    number
    title
    body
    capabilities
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  heroSubtitle
  heroTitle
  marqueeText
  introLabel
  introHeading
  introBody
  email
  phone
  location
}
    `;
export const WorkPartsFragmentDoc = gql`
    fragment WorkParts on Work {
  __typename
  clientName
  industry
  heroImage
  setupHeading
  setupBody
  catalystHeading
  catalystBody
  resolutionHeading
  resolutionBody
  impactStatement
  published
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const PhilosophyDocument = gql`
    query philosophy($relativePath: String!) {
  philosophy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhilosophyParts
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const PhilosophyConnectionDocument = gql`
    query philosophyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhilosophyFilter) {
  philosophyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhilosophyParts
      }
    }
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const WorkDocument = gql`
    query work($relativePath: String!) {
  work(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorkParts
  }
}
    ${WorkPartsFragmentDoc}`;
export const WorkConnectionDocument = gql`
    query workConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorkFilter) {
  workConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorkParts
      }
    }
  }
}
    ${WorkPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    philosophy(variables: PhilosophyQueryVariables, options?: C): Promise<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}> {
        return requester<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}, PhilosophyQueryVariables>(PhilosophyDocument, variables, options);
      },
    philosophyConnection(variables?: PhilosophyConnectionQueryVariables, options?: C): Promise<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}> {
        return requester<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}, PhilosophyConnectionQueryVariables>(PhilosophyConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    work(variables: WorkQueryVariables, options?: C): Promise<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}> {
        return requester<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}, WorkQueryVariables>(WorkDocument, variables, options);
      },
    workConnection(variables?: WorkConnectionQueryVariables, options?: C): Promise<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}> {
        return requester<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}, WorkConnectionQueryVariables>(WorkConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  